### ISSUE TITLE
Will not start without node modules

### ISSUE THREAD

**Issue by Michaelmvv** [jointheleague/lets-eat#143]
Here is the output i get:

```
W20161208-20:25:29.711(-8)? (STDERR) /Users/mikey/Desktop/git/lets-eat/.meteor/local/build/programs/server/boot.js:348
W20161208-20:25:29.712(-8)? (STDERR) }).run();
W20161208-20:25:29.712(-8)? (STDERR)    ^
W20161208-20:25:29.712(-8)? (STDERR) 
W20161208-20:25:29.712(-8)? (STDERR) Error: The babel-runtime npm package could not be found in your node_modules 
W20161208-20:25:29.713(-8)? (STDERR) directory. Please run the following command to install it:
W20161208-20:25:29.713(-8)? (STDERR) 
W20161208-20:25:29.713(-8)? (STDERR)   meteor npm install --save babel-runtime
W20161208-20:25:29.713(-8)? (STDERR) 
W20161208-20:25:29.714(-8)? (STDERR)     at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)
W20161208-20:25:29.714(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161208-20:25:29.714(-8)? (STDERR)     at require (packages/modules-runtime.js:106:16)
W20161208-20:25:29.714(-8)? (STDERR)     at packages/babel-runtime.js:139:15
W20161208-20:25:29.715(-8)? (STDERR)     at packages/babel-runtime.js:150:3
W20161208-20:25:29.715(-8)? (STDERR)     at /Users/mikey/Desktop/git/lets-eat/.meteor/local/build/programs/server/boot.js:295:34
W20161208-20:25:29.715(-8)? (STDERR)     at Array.forEach (native)
W20161208-20:25:29.716(-8)? (STDERR)     at Function._.each._.forEach (/Users/mikey/.meteor/packages/meteor-tool/.1.4.2_3.gputnz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20161208-20:25:29.717(-8)? (STDERR)     at /Users/mikey/Desktop/git/lets-eat/.meteor/local/build/programs/server/boot.js:128:5
W20161208-20:25:29.717(-8)? (STDERR)     at /Users/mikey/Desktop/git/lets-eat/.meteor/local/build/programs/server/boot.js:344:5
=> Exited with code: 1
```

**Comment by Michaelmvv** [comment]
NVM i got it
