### ISSUE TITLE
'Geocode' ReferenceError: GoogleMaps is not defined

### ISSUE THREAD

**Issue by philcruz** [jointheleague/lets-eat#24]
Exception while invoking method 'Geocode' ReferenceError: GoogleMaps is not defined
I20160302-15:42:53.303(-8)?     at [object Object].Meteor.methods.Geocode (lets-eat.js:15:15)
I20160302-15:42:53.303(-8)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20160302-15:42:53.303(-8)?     at livedata_server.js:708:19

**Comment by philcruz** [comment]
I don't see this error any more after changing the geocoding from a Meteor.method to regular function.
